### ISSUE TITLE
[CRASH] before start

### ISSUE THREAD

**Issue by ATUX522** [ZsoltMolnarrr/Wizards#11]
[crash-2023-03-04_16.09.21-client.txt](https://github.com/ZsoltMolnarrr/Wizards/files/10888452/crash-2023-03-04_16.09.21-client.txt)
I dont know if this is the right one cuz its not showing any reason why it crased it only said error 1

**Comment by ZsoltMolnarrr** [comment]
Is this a purchased version of Minecraft?

**Comment by ZsoltMolnarrr** [comment]
Can you please try updating your JVM installation?

**Comment by ATUX522** [comment]
yeah its xbox gamepass version and i already did updated my java

**Comment by ZsoltMolnarrr** [comment]
What java version did you use after updating?

**Comment by ZsoltMolnarrr** [comment]
I discovered this issue is happening on Turkish machines.
An update to fix turkish problems will soon be out.
Make sure to update **all** of your installed mods.

**Comment by ATUX522** [comment]
Yeah im playing w turkish machine thanks btw

**Comment by ZsoltMolnarrr** [comment]
Update is out.

**Comment by ATUX522** [comment]
btw it work on curse forge fabric version dont know why

**Comment by ATUX522** [comment]
thx alot tho
