### ISSUE TITLE
Crash when put on the robes then use CosmeticArmor-1.19-1.4.0 to wear cometicArmor (Fabric)

### ISSUE THREAD

**Issue by Jsnuggie** [ZsoltMolnarrr/Wizards#12]
Crash when put on the robes then use CosmeticArmor-1.19-1.4.0 to wear cometicArmor (Fabric)

**Comment by ZsoltMolnarrr** [comment]
I cannot reproduce the issue.
Please attach a crashlog, or I have to close due to non-actionability.

**Comment by Herrchanana** [comment]
Hey, I have received this issue as well. Here is an attached crashlog. 
https://pastebin.com/mtEGjjwu 

This issue only occurs when you put something over the robe in the cosmetic chest slot.

**Comment by ZsoltMolnarrr** [comment]
This looks like an incompatibility between CosmeticArmor and GeckoLib armor renderer.
I don't see what I can do.
