### ISSUE TITLE
Compatibility with BYG

### ISSUE THREAD

**Issue by CranjusMcBaller** [ZsoltMolnarrr/Wizards#14]
Included this mod in my exploration modpack and found out that, when paired with Oh the Biomes You'll Go (Fabric), wizard towers do not generate in villages. Ever. I have been trying to find places in the files that this might be fixed or somewhere in the BYG settings that might allow it to still happen, but so far nothing has worked.

Is this something only I'm experiencing, something you're working to address, or something that just won't work?

**Comment by ChoiceTheorem** [comment]
Only BYG? Do you use any village mod like Repurposed structures, Overhauled Village or Town and towers?

**Comment by ZsoltMolnarrr** [comment]
I think there is a misunderstanding here, I am fairly certain the issue reporter means CTOV and T&T villages.
