### ISSUE TITLE
villagerwizard merchant error with 1.19.2 Fabric 0.14.21

### ISSUE THREAD

**Issue by MEGATREX4** [ZsoltMolnarrr/Wizards#15]
`Skipped language file: wizards:lang/uk_ua.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 77 column 4 path $.entity.minecraft.villager.wizard_merchant)`
 
 I have checked several times and it does not want to work 
 no localisation files are downloaded, if you need any additional information, please contact us
 
 Minecraft 1.19.2 with Fabric Loader 0.14.21
[list of all mods if necessary](https://github.com/ZsoltMolnarrr/Wizards/files/12130571/modlog.txt)

**Comment by ZsoltMolnarrr** [comment]
Sorry this is non actionable for me, since I don't maintain localisations.
If you can fix the UA locale file, please do so and send it as a PR.

**Comment by SKZGx** [comment]
This is with any language, I check twice

**Comment by SKZGx** [comment]
> Sorry this is non actionable for me, since I don't maintain localisations. If you can fix the UA locale file, please do so and send it as a PR.

This is with any language, I check twice
