### ISSUE TITLE
Mod won't work along with other mods of the series

### ISSUE THREAD

**Issue by GitBoy365** [ZsoltMolnarrr/Wizards#16]
I have the mods along with the mods that are required to run the rpg series mods, but it doesn't show up at all. And the items aren't there either along with structures and villagers. It pretty much says I don't have the mods on, even though I do.

**Comment by ZsoltMolnarrr** [comment]
Make sure to install it correctly.
Use CurseForge launcher, don't drag and drop jar files manually.
