### ISSUE TITLE
Suggestion: Immersive weathering integration

### ISSUE THREAD

**Issue by DelphiDv** [ZsoltMolnarrr/Wizards#17]
Spells should effects the environnement more, doing it with immersive weathering integration would make the mods pair up really well and make the magic more dynamic/immersive and sometimes more useful:
let fire spells thaw/dry/burn blocks
ice spells freeze water, generate iscicles and turn blocks into their frozen varients
arcane spells could grow moss or something idk.

**Comment by ZsoltMolnarrr** [comment]
Hello!
Thank you for the idea, I love the enthusiasm.
I am sorry, there is no realistic chance this will be implemented, mainly because the spell engine wasn't designed for anything like this.
