### ISSUE TITLE
Can't right click with special weapon

### ISSUE THREAD

**Issue by cutekitticat** [ZsoltMolnarrr/Wizards#22]
I can't use the weapons from Marium's Soullike Weaponry,
I cannot right click to use special attacks

**Comment by ZsoltMolnarrr** [comment]
Discord FAQ

**Weapons with a right click action, now conflict with automatically assigned spell casting feature. How can I fix it?**
You have multiple options:
A) Disable automatically assigning spell casting capability, set `"add_spell_casting_to_swords": false` (in `config/spell_engine/server.json5`)
B) Add the specific item, or the all items from a mod to the related blacklist. `"blacklist_spell_casting_regex"`
The blacklist is a regex. It is matched against item ids.
Example: to disable all weapons from `banana` and `apple` mods, use: `"banana:|apple:"`
Example: to disable a weapons with the following id `orange:orange_sword`, use: `"orange:orange_sword"`
C) Disable spell casting for a specific item using data files https://github.com/ZsoltMolnarrr/SpellEngine#%EF%B8%8F-disabling-spell-casting-capability-for-weapons
