### ISSUE TITLE
AOE and Instant Spells should affect players too

### ISSUE THREAD

**Issue by FumpleWumper** [ZsoltMolnarrr/Wizards#23]
Right now the only spells in this mod that can affect other players are targeted projectile spells. I understand this may be to make cooperative teams easier but it's also not very good when people are trying to purposefully fight each other with this mod which is the case of me and my friends...

Could there be a way to fix this? Perhaps if players have disabled the "Filter Invalid Targets" option in the Spell Engine settings, it'll allow them to use AOE and Instant Casts on other players? Or some other item is added that allows players to tag each other as "allies", thus preventing them from hitting each other with these spells.

Either way I'd just really like for all the spells to be usable in PvP...

**Comment by ZsoltMolnarrr** [comment]
Discord server FAQ:

**Why can I not hit other players or villagers with area spells (like Arcane Beam)?**
The default configuration is PVE oriented, friendly towards villagers and other players.
Put players into different teams to allow hurting each-other.
Alternatively you can change this in Spell Engine server config (`config/spell-engine/server.json5`)
