### ISSUE TITLE
Soul Runes and Lightning rune DLC

### ISSUE THREAD

**Issue by Vampzula** [ZsoltMolnarrr/Wizards#25]
Will DLC for Soul and lightning be released soon? Paladin & Priest is a very cool mod and it would be nice to see something similar with the remaining runes, as well as new types of weapons from other materials! 

Tnx Google translate

**Comment by ZsoltMolnarrr** [comment]
All relevant information is available on the community discord, which is linked to every mod page (CurseForge and Modrinth)
