### ISSUE TITLE
[question] May I use your RPG series mods (paladins, wizards, archers), in my public modpack.

### ISSUE THREAD

**Issue by netcore10** [ZsoltMolnarrr/Wizards#30]
Hi, I'm currently working on a modrinth SMP modpack and sometimes modrinth requires permission from mods that are ARR. Is it okay to use your RPG series of mods (Archers, paladins, and wizards) in our public modpack?

**Comment by ZsoltMolnarrr** [comment]
Hello!
Yes you are welcome to use them as long as the modpack is distributed only via official platforms (CurseForge and Modrinth).
Other kinds of distributions are not allowed.
