### ISSUE TITLE
(Request) Compatible with Curios API

### ISSUE THREAD

**Issue by wsxiya** [ZsoltMolnarrr/Wizards#31]
Using the Sinytra Connector will allow your mod to run perfectly in forge, but can you make a version for forge that replaces the Curios API with front-end Trinkets?

**Comment by ZsoltMolnarrr** [comment]
This is an issue for Spell Engine actually.

However supporting Curious in a pure fabric stack is not possible as far as I know.

Nor do I actually have time for this implementation in the near future.
