### ISSUE TITLE
Are you open to pull requests to add compatibility with other mods?

### ISSUE THREAD

**Issue by ArtofShannonLee** [ZsoltMolnarrr/Wizards#32]
Hi! I know your mods are all copyrighted and 100% respect that. So, I wanted to check if you would be open to us making a pull request sometime in the future, to allow compatibility with our mod? I understand that it will likely depend on how well we execute our mod. I'm just wondering if it's a possibility at all or if that's not something you do? Sorry if this is a silly question- I've only worked with open-source stuff before.

**About our mod:**
My team and I are in the early stages of developing a mod addon for Minecraft Comes Alive: Reborn (forge and fabric) which, in addition to giving MCA an aesthetic fantasy make-over, adds MCA-style villagers of various DnD-style fantasy races, with unique attributes. As with base MCA, all of the villagers will look unique and players will be able to befriend, romance and have kids with them, passing on their traits. Most importantly, they'll be able to build adventuring parties with them.

**What we'd like to do:**
My understanding of your awesome mod series is that it is predominantly targeted at use on a server with multiple players. I'd like to add the possibility (when MCA Fantasy is also installed) to find rare MCA Fantasy villagers who have an RPG class. This would mean players can get a similar experience of play even if they're playing single-player. The villagers wouldn't necessarily have the full abilities of players, but an appropriate approximation for NPCs; and the aesthetics of their attacks and spells etc would match players', which would be nice and immersive. Your mods are especially appealing to me for this purpose because I understand that your classes are intended to be customisable, giving players lots of creative control. 

Is this something you would consider allowing us to do, when the time comes? 

Thank you very much for your time. :)

**Comment by ZsoltMolnarrr** [comment]
Hi,
Thank you for respecting the license. To clarify, the main purpose of the chosen license is to protect the assets bundled into the mod, those were made by professionals (at a fairly high cost).
Can you explain why would it be necessary to add any code to this project?

**Comment by ArtofShannonLee** [comment]
Hello,
Thank you for your response. I'm not sure how best to accomplish the goal yet, but was mainly asking in case it was never a possibility, to save lots of work. Now that I've had more time to look at how your mods work, I can see that, in theory, I should be able to make my own Classes by depending on your Spell Engine and the fighting mods, similarly to how you have with this (Wizards), Paladins and Priests and Archers; and I shouldn't have to actually change anything. But, to clarify, that is how they're intended to be used, right? I wouldn't want to misuse them in any way, that's all.

**Comment by ZsoltMolnarrr** [comment]
Yes RPG Series mods are content mods, generally not to be modified or reused by other parties, while Spell Engine is open source licenesed, so anyone is free to create their own classes.
Closing this issue, feel free to reach out on Discord.

**Comment by ArtofShannonLee** [comment]
Okay. Thank you very much for your time.
