### ISSUE TITLE
Uncraftable wands

### ISSUE THREAD

**Issue by Shtwick** [ZsoltMolnarrr/Wizards#33]
As said in title, using EMI, I am unable to craft any wand.
Not only that, but even attempting to craft it like shown in the images does not work.
Any fix, maybe in config?

**Comment by ZsoltMolnarrr** [comment]
I don't understand, nor do I have an idea what could be causing this.
Wizards (and all of the RPG Series mods) use absolutely standard data driven crafting recipes.
Hence there isn't even anything I can do about this, as far as I know.

Feel free to reopen the issue, when the specifics of how exactly I could be fixing this are known.
