### ISSUE TITLE
Update crash

### ISSUE THREAD

**Issue by zc1108aaa** [ZsoltMolnarrr/Wizards#35]
spell_engine-0.11.0+1.20.1
wizards-fabric-0.9.23+1.20.1
No problem with startup

spell_engine-0.12.5+1.20.1
wizards-1.0.5+1.20.1S
tart crash

[latest.log](https://github.com/ZsoltMolnarrr/Wizards/files/13958573/latest.log)

**Comment by ZsoltMolnarrr** [comment]
Make sure to update ALL of your mods.
Spell Power Attributes are out of version sync.

To avoid such problems it is recommended to use a proper mod launcher that resolves dependencies and shows mod updates being available (such as CurseForge and Modrinth desktop apps).
