### ISSUE TITLE
Request: Add keybind support for rune abilities

### ISSUE THREAD

**Issue by TFoley1** [ZsoltMolnarrr/Wizards#36]
I suggest that keybind support is added mostly for two reasons.

One: Using a Tome with a melee weapon doesn't conflict with other gameplay elements 
Ex: Trident or other mod packs that allow for riptide use. Or choosing between blocking with a shield or using your first spell.

Two: Accessibility, it's just nice to have options :)

**Comment by ZsoltMolnarrr** [comment]
Spell Engine has a keybind that allows you to skip spell casting, called "Bypass Spell Hotbar".
Assign something to it, hold it to use offhand shield or item perk.
