### ISSUE TITLE
Some Spells seem to have no interaction in pvp

### ISSUE THREAD

**Issue by DaanSchar** [ZsoltMolnarrr/Wizards#4]
The following spells don't interact with other players when casted on them:

* Fire Breath
* Meteor
* Arcane Beam
* Frost Bold

fabric 1.19.2 0.14.12

**Comment by ZsoltMolnarrr** [comment]
Hello!
Did you try putting players into different teams?

**Comment by ZsoltMolnarrr** [comment]
Or did you change the server config of Spell Engine?

**Comment by DaanSchar** [comment]
I re-started the world fresh to test it again. So no teams, no configs. nothing

**Comment by ZsoltMolnarrr** [comment]
The configuration is PVE oriented by default, players are meant to hurt eachother when inside different teams.
Change Spell Engine server config if you don't like it.
Feel free to reopen if not solved.
