### ISSUE TITLE
Wizards Items disappear when using Spell Binding Table

### ISSUE THREAD

**Issue by Aromboy** [ZsoltMolnarrr/Wizards#40]
I detected that when the player gets any item for wizards from creative mode and then use the Spell Binding Table it disappear. It's annoying because when I try to enchant the spellbook for wizards it vanish.

**Comment by ZsoltMolnarrr** [comment]
I am unable to reproduce this issue at tall.

**Comment by ZsoltMolnarrr** [comment]
Please provide more details about how to reproduce this

**Comment by Aromboy** [comment]
Being in creative mode, pick an item for wizards and put it in your inventory. Then rigth click in Spell Binding Table, and when you do that, the item for wizards that you picked just dissapears

**Comment by ZsoltMolnarrr** [comment]
Unable to reproduce the issue, please provide all specific version information.
