### ISSUE TITLE
Rune Pouch

### ISSUE THREAD

**Issue by jimmytrouser** [ZsoltMolnarrr/Wizards#42]
Any chance of a Rune Pouch to keep the runes together in one place?

Remember Roots having something similar for its casting system.

Thanks.

**Comment by ZsoltMolnarrr** [comment]
The idea of a Rune Pouch has been on the roadmap for quite a while, and has definitely not been forgotten about.

Unfortunately it is rather complicated to implement, I didn't have free time for it yet.

Closing this issue because this idea belongs to the _Runes_ project.
