### ISSUE TITLE
Request: Adding more items related to the Souls element, for Necromancer!

### ISSUE THREAD

**Issue by FumpleWumper** [ZsoltMolnarrr/Wizards#43]
With the recent addition of the Necromancer class, a severe lack of Soul element spells has arised, it would be great to get a spellbook and some gear to go along with this new class, perhaps based around sucking the health out of other entities, shortly becoming invulnerable to damage, turning undead into allies, or even phasing through walls? Either way expanding on the Necromancer's options would be great, thank you for reading, and thank you for the work you're putting in the mod!

**Comment by ZsoltMolnarrr** [comment]
Hello!
Soul Magic is on the development roadmap (visible on the Discord).
Such content will be shipped as a standalone project.
