### ISSUE TITLE
[QUESTION/SUGGESTION] more classes/subclasses?

### ISSUE THREAD

**Issue by MaximusXgamer** [ZsoltMolnarrr/Wizards#45]
I don't know where else I can ask this question, so I might as well ask here.

Is there a possibility there may be more classes in the future? (stuff like Warriors, Rogues, Druids, Bards, etc.)

And, if so, are you also planning for subclasses of the new classes and the already pre-existing classes? (like how the Wizard 'class' has three different spell tomes with different spells, unlike the other classes which only have one each.)

**Comment by ZsoltMolnarrr** [comment]
Hello!
Check out the public roadmap posted on our Discord server, also please use the server for conversation, instead of GitHub issues.
More classes are planned.
Classes now have 4 instead of 3 spells.
Additional classes exist from other developers, search for "Spell Engine" on CurseForge.

**Comment by MaximusXgamer** [comment]
Thank you!
