### ISSUE TITLE
No slot for spell book

### ISSUE THREAD

**Issue by YagaSero** [ZsoltMolnarrr/Wizards#46]
Good day! In my opinion, I installed all the necessary APIs for the mod to work, but the game does not have a slot for a spell book in the inventory and I cannot use them. (check screenshot)
![Снимок экрана (2)](https://github.com/ZsoltMolnarrr/Wizards/assets/167211601/2629c49c-fe03-4089-9c0c-5e7dc9af273f)

Please help solve the problem. I dreamed of playing "perfect hardcore minecraft" on vacation, but the mod just doesn't work fully :(

Below is a list of installed APIs:

AdaptiveTooltips-1.3.0-fabric-1.20.2
azurelibarmor-fabric-1.20.1-2.0.3
bettercombat-fabric-1.8.5+1.20.1
chefs-delight-1.0.3-fabric-1.20.1
cicada-lib-0.6.2+1.20.1-and-below
cloth-config-11.1.118-fabric
darkmining-forge-1.20.4-1.1.3
DistantHorizons-fabric-2.0.2-a-dev-1.20.1
do_a_barrel_roll-fabric-3.5.4+1.20.1
fabric-api-0.92.1+1.20.1
farmers-delight-fabric-1.4.3
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
indium-1.0.30+mc1.20.4
InventorySorter-1.9.0-1.20
iris-1.7.0-snapshot+mc1.20.1-7f0ecaa-dirty
jei-1.20.1-fabric-15.2.0.23
Just-Enough-Farmers-Recipes-Mod-Fabric-1.20.1
modmenu-7.2.2
player-animation-lib-fabric-1.0.2-rc1+1.20
runes-fabric-0.9.11+1.20.1
sodium-fabric-0.5.8+mc1.20.1
spell_engine-0.14.3+1.20.1
spell_power-0.10.2+1.20.1
TreeChop-1.20.1-fabric-0.19.0
XaerosWorldMap_1.38.3_Fabric_1.20
yet-another-config-lib-fabric-3.2.2+1.20
wizards-1.2.0+1.20.1

**Comment by YagaSero** [comment]
UPD: I installed the trinkets API and it worked! If anyone needs it, here is the page: https://modrinth.com/mod/trinkets

**Comment by ZsoltMolnarrr** [comment]
Unfortunately CurseForge new frontend currently not displaying the required mods to be installed.
Trinkets was removed from Fabric mod requirements, so Sinytra Connector Forge users aren't forced to use Trinkets.
There is nothing I can do to improve this issue currently.
