### ISSUE TITLE
Only one spell

### ISSUE THREAD

**Issue by Sigma372** [ZsoltMolnarrr/Wizards#48]
Every spell book only has one accessible spell on the table and the rest of them are just a bunch of flashing symbols and letters that I can't use. I try the bind spell tables but for example the flame tome only has fireball and the rest is just flashing symbols.

**Comment by ZsoltMolnarrr** [comment]
Bookshelves my good person :)

**Comment by Sigma372** [comment]
I covered the place in bookshelves, I dont think there was a single block within 3 chunks that didn't have a bookshelf
