### ISSUE TITLE
Only one spell (response)

### ISSUE THREAD

**Issue by Sigma372** [ZsoltMolnarrr/Wizards#49]
Adding bookshelves did not work. I have enough exp, enough shelves, enough lapis, and I
 tried building both the table and the tomes from scratch but nothing is working. I also downloaded every recommended and required side mod from the description but nothing changes it.
![Screenshot (3)](https://github.com/ZsoltMolnarrr/Wizards/assets/169607817/2cc87903-22d8-4c5f-857a-be9da3c3c90e)

**Comment by Sigma372** [comment]
And this problem was still here before adding other mods

**Comment by ZsoltMolnarrr** [comment]
Bookshelves my good person :)
