### ISSUE TITLE
List of Spells?

### ISSUE THREAD

**Issue by itsdinkd** [ZsoltMolnarrr/Wizards#5]

**Comment by ZsoltMolnarrr** [comment]
No actionable information in this issue.
Please join Discord for conversation and QnA.

**Comment by itsdinkd** [comment]
Could have at least provided a discord link :)

**Comment by ZsoltMolnarrr** [comment]
Sorry, all mod pages showcase the link, I thought you saw it
https://discord.gg/KN9b3pjFTM
