### ISSUE TITLE
Wizards (and all other RPG Series mods) incorrectly display with Ledgendary Tooltips

### ISSUE THREAD

**Issue by PolyframeX** [ZsoltMolnarrr/Wizards#50]
When playing with Fancy Tooltips and any of the RPG Series mods.

![image](https://github.com/ZsoltMolnarrr/Wizards/assets/80133652/5cd0cf29-9b7b-49c4-b9b7-90e55c7561e6)

Minecraft: 1.20.1
Fabric Loader: 0.15.11
FAPI: 0.92.1
Wizards: 1.2.0
Ledgendary Tooltips: 1.4.5

**Comment by ZsoltMolnarrr** [comment]
This problem is a conflict between Legendary Tooltips and AzureLib armor.
There is nothing I can do within such content mods (Wizards, Paladins, etc...), to fix this problem.
