### ISSUE TITLE
Once again, only one spell.

### ISSUE THREAD

**Issue by Sigma372** [ZsoltMolnarrr/Wizards#52]
I have tried adding bookshelves many times and once again it does not work. I don't know if the mod is broken or if I'm missing a mod that it pairs with but either way adding bookshelves is not helping

**Comment by ZsoltMolnarrr** [comment]
Unable to reproduce.
Make sure to use vanilla bookshelves.

**Comment by susan3333333** [comment]
If you have cheats enabled, try in creative so no other factors matter, with a vanilla everything enchanting table/bookshelf setup to see if the bookshelves are the issue maybe? Tho if another mod interferes with them registering properly, they might have fixed it to work with the enchanting table?
