### ISSUE TITLE
[Bug] Wands don't register runes in my inventory.

### ISSUE THREAD

**Issue by lostdoge08** [ZsoltMolnarrr/Wizards#54]
I am sure this is a mod incompatibility, but unsure which mod. 

For example, when using a wand that requires fire runes, and I have fire runes on me, it still says I am missing them.
In creative, wands work perfectly fine, as they don't require runes.

I am on the latest version of the mod and all its dependencies for 1.20.1 if that helps at all.

If there is anything else you would like me to add or test, please let me know.

**Comment by ZsoltMolnarrr** [comment]
I am unable to debug the custom modpack setups of each individual player.
Please provide specific details about which mod is causing the problem, to make this issue actionable.
