### ISSUE TITLE
[FORGE] Curious Incompatibility

### ISSUE THREAD

**Issue by doemty** [ZsoltMolnarrr/Wizards#56]
![image](https://github.com/user-attachments/assets/04f42ab8-8e1a-4f1f-823c-cb6d7fec92f8)
I installed Curious API (and mod, that uses it) and spellbooks broke (I have only first fire spell and all weapons use this spell, for example mace and spear). I do not sure if it is a problem of mod or Trinkents.
Hope you know solution how to make all mods work together! 🙏

**Comment by ZsoltMolnarrr** [comment]
Curious is not supported at the moment, since these are primarily Fabric projects.
Trinkets needs to be used, or hold your spellbook in your offhand.

**Comment by doemty** [comment]
> Curious is not supported at the moment, since these are primarily Fabric projects. Trinkets needs to be used, or hold your spellbook in your offhand.

![image](https://github.com/user-attachments/assets/60d8c7bd-00ca-42be-8ef2-588a21b0bdba)
![image](https://github.com/user-attachments/assets/f5802526-2fdc-4f8f-8122-57d4dd303666)
 It doesn't work :(
