### ISSUE TITLE
Tome book (and all other spell books os theRPG series) disappear when you die

### ISSUE THREAD

**Issue by VetGet** [ZsoltMolnarrr/Wizards#57]
I'm having this problem on my server where the items that go in the mod slots simply disappear when the player dies, **including the jewelry mod**, I'm using the gravestone mod by the way, I imagine it could be the culprit, but from the tests I can't seemed. **HELP**

**Comment by ZsoltMolnarrr** [comment]
Please specify all the versions (of my
Mods) you are using

**Comment by VetGet** [comment]
Minecraft: 1.20.1
Loader: Farbric 0.15.11
Wizards: 1.2.2
Paladins & Priests 1.3.0
Rogues & Warriors 1.0.9
Archers: 1.2.5
Jewelry: 1.3.4
Gravestones (by geometrically) 1.15

**Comment by VetGet** [comment]
Hello, @ZsoltMolnarrr. I would like to know if there has been any progress in discovering the possible error that I presented, I am receiving constant complaints from players on my server.  I will wait for your statement as soon as possible. Tnks again.

**Comment by ZsoltMolnarrr** [comment]
This seems to be an underlying incompatibility between trinkets and Gravestones, which I am unable to resolve.
I recommend repalcing Gravestones with "You are in grave danger".
