### ISSUE TITLE
Can I call this API and how can I reference this module?

### ISSUE THREAD

**Issue by 970100646** [ZsoltMolnarrr/Wizards#60]

**Comment by ZsoltMolnarrr** [comment]
This is not an API, but a content mod.

The following APIs are available:
- Spell Engine https://github.com/ZsoltMolnarrr/SpellEngine
  - ⚠️ Unstable API, mostly undocumented
  - Used for creating spells, spellbooks
- Spell Power Attributes https://github.com/ZsoltMolnarrr/SpellPower
  - ✅ Stable API, documented
  - Used primarily for creating armor and weapons pieces with Spell Power bonuses, so spell classes can use them
