### ISSUE TITLE
First Person Staff spell casting animation visible when HUD disabled(F1)

### ISSUE THREAD

**Issue by jaredmontoya** [ZsoltMolnarrr/Wizards#63]
When you press F1 to remove all HUD(hands included) and then cast a spell you can see the animated staff.
I consider this a bug, but it doesn't seem too severe at first. What made me report this is that when you use a first person model mod like:
https://modrinth.com/mod/real-camera
and possibly(not tested but I think it has the same issue)
https://modrinth.com/mod/first-person-model

you can still see the third person animation that your character is doing because of those mods plus the first person animation that doesn't get hidden. As a result we have two animations overlaying on top of each other and it looks ugly while would be absolutely perfect if not for the first person animation. That's why I think this needs fixing. Please make it so that the first person staff animation is compatible with real camera. Also if that's not too much work, can you update the 1.20.1 version to include this fix? That's where all other mods that I use together with your mod are at the moment.

**Comment by jaredmontoya** [comment]
Also, I noticed that you can't see the robe in first person with those mods. But it does not look as broken as the overlaying casting animation and might even be good in case of the hat because the hat doesn't block your view with it's brim(although it's not realistic).

**Comment by OarisHunter** [comment]
Seconding the observation of the dual animations, and the desire to see it fixed. Having the armor be visible in first person with those mods would be a nice plus

**Comment by ZsoltMolnarrr** [comment]
This is an issue between Spell Engine and Real Camera most likely.

**Comment by ZsoltMolnarrr** [comment]
Will be fixed by the next update of Spell Engine, that allows disabling first person animations.
