### ISSUE TITLE
Issues with Spells

### ISSUE THREAD

**Issue by EstrelaWasHere** [ZsoltMolnarrr/Wizards#67]
I have an issue where I can't cast any spells past the primary spell. Every spell after that is unusable for me, even with the runes and everything. I have the same mods as my friends, identical to their files and I've even tried completely reinstalling, but it doesn't work for me. My friends have no issue using the spells I can't use. Is there a solution to this?

Would be grateful if this could be solved, thanks! <3

**Comment by ZsoltMolnarrr** [comment]
Please provide more details, preferably some video footage.

**Comment by ZsoltMolnarrr** [comment]
The mod definitely has no specific issue related.

Please join our Discord server, where you can share your use case with the community and receive specific recommendations.
