### ISSUE TITLE
no dealing damage

### ISSUE THREAD

**Issue by caetanoarturo** [ZsoltMolnarrr/Wizards#68]
some skills only work on mobs, in combat against players they are not causing damage.

**Comment by ZsoltMolnarrr** [comment]
FAQ from our discord.

> **Why can I not hit other players or villagers with area spells (like Arcane Beam)?**
> The default configuration is PVE oriented, friendly towards villagers and other players.
> Put players into different teams to allow hurting each-other.
> Alternatively you can change this in Spell Engine server config (`config/spell-engine/server.json5`)

(Edited, pasted the wrong answer at first)
