### ISSUE TITLE
Spells Wont Damage Their Targets

### ISSUE THREAD

**Issue by DistantDig** [ZsoltMolnarrr/Wizards#8]
Ive been having a bit of an issue getting some of the spells to actually do damage to certain targets. Currently im in version fabric-0.9.9+1.19 of Wizards. Whenever I cast any spell besides the basic elemental projectile, it wont actually do damage to certain mobs. I can get the spells to damage an iron golem, but i cant get them to damage a villager for example.

**Comment by ZsoltMolnarrr** [comment]
Default Friend or Foe configuration is PVE oriented and friendly towards villagers, assuming you are trying to save them not kill them.
Open `config/spell_engine/server.json5` to change these.
