### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by MinecraftModderDailyDoseOfMods** [ZsoltMolnarrr/Wizards#9]
I Load this mod with better combat and it's libary mods.It crash like this:
CrashyLink:Best trobleshoot
https://crashy.net/8f512157-87ef-436d-9574-03b0338d871e
Crash Report:
[crash-2023-02-19_16.02.57-client.txt](https://github.com/ZsoltMolnarrr/Wizards/files/10776865/crash-2023-02-19_16.02.57-client.txt)

**Comment by ZsoltMolnarrr** [comment]
Update **all** of your mods to the latest version.
I recommend using CurseForge launcher. It shows you which mods need updating, and updates can be performed by a single click.
